### ISSUE TITLE
Support live adjust of certain camera parameters

### ISSUE THREAD

**Issue by nclack** [acquire-project/acquire-video-runtime#40]
To support lightsheet, it's helpful to control exposure time and slit width live.

For the orca fusion this is
- [x] acquire-project/cpx#42
- [x] acquire-project/cpx#43
- [x] acquire-project/cpx#44
- [x] ~add camera prop global vs rolling shutter~

Currently parameter set/get stops the camera (at least for dcam). So another task is to:
- [ ] acquire-project/cpx#46

Rolling shutter w lightsheet does exposure reset just before a line is exposed again. Setting lightsheet mode might imply rolling shutter.

When lightsheet is enabled. HCImage enables the following advanced props:
* `READOUT_DIRECTION`
* `TRIGGER_GLOBAL_EXPOSURE`

`TIMING_EXPOSURE` is not enabled - constitutively set to `ROLLING`.

May need to set some "Speed" parameter to "Fast" as opposed to quiet or standard.
